NumPy Arrays

In [1]:
import numpy as np

In [2]:
myList = [1,2,3]


In [3]:
type(myList)

list

In [5]:
np.array(myList)

array([1, 2, 3])

In [6]:
myarr=np.array(myList)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.random.rand(5,2)

array([[0.14336612, 0.55066905],
       [0.47671596, 0.28195743],
       [0.9561635 , 0.09131143],
       [0.5905763 , 0.61367851],
       [0.95648892, 0.17204183]])

In [37]:
np.random.randn(10)

array([-0.45479843,  1.93522301, -0.16112167,  1.62115732, -0.64245241,
        1.55115784,  0.6830627 ,  0.08908755,  2.16914297,  0.23639121])

In [38]:
np.random.randn(2,3)

array([[ 0.58175387,  2.42542668,  0.33047538],
       [ 0.50247628, -0.80560452,  0.67541394]])